# configuration for training market1501

dataset:
    name: market1501

aug:
    resize_size: [176, 80]
    random_mirror: True
    pad: 10
    random_crop: True

test:
    batch_size: 128

network:
    name: 'Baseline'
    backbone: 'resnet18'
    last_stride: 2
    gpus: '0'

