dataset:
    name: facereid

aug:
    resize_size: [80,80] 
    random_mirror: True
    pad: 7
    random_crop: True

train:
    optimizer: 'Adam'
    lr: 0.00035
    num_epochs: 121
    p_size: 12
    k_size: 5
    sampler: 'triplet'
    wd: 0.0005
    step: [40, 70]
    factor: 0.1
    warmup_epoch: 10
    warmup_begin_lr: 0.0000035
    loss_fn: 'softmax_triplet'

test:
    batch_size: 128

network:
    name: 'Resnetsmall'
    last_stride: 1

misc:
    eval_step: 10
    save_step: 10
    log_interval: 20


